### ISSUE TITLE
Bug in waffle basic

### ISSUE THREAD

**Issue by kakanic2086** [asjadnaqvi/stata-waffle#3]
When running the basic version of the waffle command this error occurs: option legend() not allowed

clear
sysuse pop2000, clear

// generate a categorical variable

gen agecat = .
replace agecat = 1 if agegrp <= 3
replace agecat = 2 if inrange(agegrp, 4, 13)
replace agecat = 3 if agegrp >=14 

tab agegrp agecat 
lab de agecat 1 "<15" 2 "15-64" 3 "> 65+"
lab val agecat agecat

waffle white black asian indian

**Comment by asjadnaqvi** [comment]
The new upload should fix this.

**Comment by asjadnaqvi** [comment]
Fixed in v1.11
