### ISSUE TITLE
Turn off labels?

### ISSUE THREAD

**Issue by ave05mwg** [asjadnaqvi/stata-waffle#5]
Thank you very much for an awesome command. I am hoping to be able to use it in reports for the NYS department of health, since waffles are much easier to compare than pie charts.

I have a question/request. The labels under each over() item specify the total. But if you are using the showpct and percent options, the total is 100% for each waffle, which makes it silly to put (100%) next to the label. See example. Is there a way to kill the (100%)'s? If not, I would request that it be added.

![WaffleExample](https://github.com/user-attachments/assets/e32422e2-9a64-4364-a395-b8b0e29ed7f5)

(My next task is to figure out the palette options; I may be submitting another question or request after that.)

Again, thank you!

**Comment by asjadnaqvi** [comment]
I will update it tonight or tomorrow!

**Comment by ave05mwg** [comment]
That is impressive!

**Comment by asjadnaqvi** [comment]
Version v1.23 is now up. Install directly from GitHub until up on SSC:

```stata
net install waffle, from("https://raw.githubusercontent.com/asjadnaqvi/stata-waffle/main/installation/") replace
```

If using label wrapping install `graphfunctions` directly from GitHub until up on SSC:

```stata
net install graphfunctions, from("https://raw.githubusercontent.com/asjadnaqvi/stata-graphfunctions/main/installation/") replace
```

Here is a preview of the `noval` option:

```stata
sysuse pop2000, clear

label list

gen agecat = .
replace agecat = 1 if agegrp <= 3
replace agecat = 2 if inrange(agegrp, 4, 8)
replace agecat = 3 if inrange(agegrp, 9, 13)
replace agecat = 4 if agegrp >=14 

tab agegrp agecat 
lab de agecat 1 "<15" 2 "15-39" 3 "40-64" 4 "> 65+"
lab val agecat agecat

waffle white black asian indian, over(agecat) note("") percent noval
```

![waffle_noval](https://github.com/user-attachments/assets/5d16eb87-c341-44b2-90a4-1654241030c6)

**Comment by ave05mwg** [comment]
Wow! Thank you!

**Comment by ave05mwg** [comment]
I have installed the update and (of course) it works great.
